### ISSUE TITLE
OSError: sndfile library not found

### ISSUE THREAD

**Issue by loretoparisi** [xserrat/docker-facebook-demucs#2]
The build is ok, but when running with `make run path/to/file.mp3` I get the following error:

```
docker run --rm -i \
		--name=demucs \
		-v /Users/loretoparisi/Documents/Projects/AI/docker-facebook-demucs-main/input:/data/input \
		-v /Users/loretoparisi/Documents/Projects/AI/docker-facebook-demucs-main/output:/data/output \
		-v /Users/loretoparisi/Documents/Projects/AI/docker-facebook-demucs-main/models:/data/models \
		facebook/demucs:latest \
		"python3 -m demucs.separate --dl -n demucs -d cpu --out /data/output --models /data/models \
		/data/input/"
Traceback (most recent call last):
  File "/opt/conda/envs/demucs/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/demucs/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/lib/demucs/demucs/separate.py", line 13, in <module>
    import torchaudio as ta
  File "/opt/conda/envs/demucs/lib/python3.9/site-packages/torchaudio/__init__.py", line 15, in <module>
    from torchaudio.backend import (
  File "/opt/conda/envs/demucs/lib/python3.9/site-packages/torchaudio/backend/__init__.py", line 2, in <module>
    from . import utils
  File "/opt/conda/envs/demucs/lib/python3.9/site-packages/torchaudio/backend/utils.py", line 7, in <module>
    from . import (
  File "/opt/conda/envs/demucs/lib/python3.9/site-packages/torchaudio/backend/soundfile_backend.py", line 15, in <module>
    import soundfile
  File "/opt/conda/envs/demucs/lib/python3.9/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found
make: *** [run] Error 1
```

I assume that `libsndfile` should be in the `Dockerfile` right?

Also, after `make build` I cannot see the downloaded model's files in the volumes folders:

```
ip-192-168-178-30:docker-facebook-demucs-main loretoparisi$ tree -L 3
.
├── Dockerfile
├── LICENSE
├── Makefile
├── README.md
├── input
├── models
└── output
```

**Comment by xserrat** [comment]
Hi @loretoparisi ,

I've checked the installed packages and it's not present in the list:

```bash
docker run -it --rm facebook/demucs:latest "conda list | grep libsndfile"
```

The available packages are:

```bash
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
attrs                     20.3.0                   pypi_0    pypi
blas                      1.0                         mkl  
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py39hf3d152e_1    conda-forge
cffi                      1.14.5                   pypi_0    pypi
cudatoolkit               11.1.1               h6406543_8    conda-forge
diffq                     0.1.0                    pypi_0    pypi
ffmpeg                    4.3.1                hca11adc_2    conda-forge
ffmpeg-python             0.2.0                    pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2                   pypi_0    pypi
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
jsonschema                3.2.0                    pypi_0    pypi
julius                    0.2.3                    pypi_0    pypi
lame                      3.100             h7f98852_1001    conda-forge
lameenc                   1.3.1                    pypi_0    pypi
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libuv                     1.41.0               h7f98852_0    conda-forge
llvm-openmp               11.1.0               h4bd325d_1    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
mkl-service               2.3.0            py39h07f9747_2    conda-forge
mkl_fft                   1.2.0            py39h1dff97c_1    conda-forge
mkl_random                1.0.2            py39h63df603_0  
musdb                     0.4.0                    pypi_0    pypi
museval                   0.4.0                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
ninja                     1.10.2               h4bd325d_0    conda-forge
numpy                     1.19.2           py39h89c1606_0  
numpy-base                1.19.2           py39h2ae0177_0  
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pandas                    1.2.4                    pypi_0    pypi
pip                       21.1               pyhd8ed1ab_0    conda-forge
pyaml                     20.4.0                   pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
python                    3.9.2           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.9                      1_cp39    conda-forge
pytorch                   1.8.1           py3.9_cuda11.1_cudnn8.0.5_0    pytorch
pytz                      2021.1                   pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.1                  h46c0cb4_0    conda-forge
scipy                     1.6.3                    pypi_0    pypi
setuptools                49.6.0           py39hf3d152e_3    conda-forge
simplejson                3.17.2                   pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
soundfile                 0.10.3.post1             pypi_0    pypi
sqlite                    3.35.5               h74cdb3f_0    conda-forge
stempeg                   0.2.3                    pypi_0    pypi
tk                        8.6.10               h21135ba_1    conda-forge
torchaudio                0.8.1                      py39    pytorch
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
treetable                 0.2.4                    pypi_0    pypi
typing_extensions         3.7.4.3                    py_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
x264                      1!161.3030           h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

@loretoparisi, I've created this PR #3 with a fix. Thanks for your comment :)

@adefossez , do you know if there's any update in your part that makes this package mandatory to run the demucs? Thanks!

**Comment by adefossez** [comment]
Yes torchaudio is now required. However,  normally it doesn't depend on libsndfile except on windows. @loretoparisi are you running this from windows ?

**Comment by loretoparisi** [comment]
@adefossez nope, the docker host is mac, but I'm running within the provided docker container.

**Comment by adefossez** [comment]
@loretoparisi can you test with the latest master if this is still an issue ? otherwise we will add the installation of libsndfile to the docker image.

**Comment by loretoparisi** [comment]
@adefossez yep! Let me try

**Comment by loretoparisi** [comment]
```
Separated tracks will be stored in /data/output/demucs_quantized
Separating track /data/input/test.mp3
ip-192-168-178-30:docker-facebook-demucs loretoparisi$ tree -L 4
.
├── Dockerfile
├── LICENSE
├── Makefile
├── README.md
├── input
│   └── test.mp3
├── models
└── output
    └── demucs_quantized
        └── test
            ├── bass.wav
            ├── drums.wav
            ├── other.wav
            └── vocals.wav

5 directories, 9 files
```

@adefossez @xserrat great! it works now 💯

**Comment by loretoparisi** [comment]
@xserrat just one thing, I cannot see any model downloaded to `models/` folder, even if the volume seems to be correctly attached when running

```
docker run --rm -i \
		--name=demucs \
		-v /Users/loretoparisi/Documents/Projects/AI/docker-facebook-demucs/input:/data/input \
		-v /Users/loretoparisi/Documents/Projects/AI/docker-facebook-demucs/output:/data/output \
		-v /Users/loretoparisi/Documents/Projects/AI/docker-facebook-demucs/models:/data/models \
		facebook/demucs:latest \
		"python3 -m demucs.separate --out /data/output --models /data/models \
		/data/input/test.mp3"
```

so I tried
```
docker run --rm -i  --name=demucs facebook/demucs:latest bash
python3 -m demucs.separate --out /data/output --models /data/models test.mp3
100%|██████████████████████████████████████████████████████████████████████████| 30.0/30.0 [00:18<00:00,  1.59seconds/s]Separated tracks will be stored in /data/output/demucs_quantized
Separating track test.mp3
cd /data/models
ls
 ```

**Comment by adefossez** [comment]
Yes, I'm using PyTorch Hub API now so models are stored in some standard location in ~/.cache. 

I think it is fine to remove the models partition, the only use case would be to use a model that someone trained themselves, but then they will likely have the full thing setup with Anaconda.

**Comment by loretoparisi** [comment]
Got it, maybe optionally it could be useful to pass a custom location via the env 

$TORCH_HOME

So like, by defaults 

docker run -e TORCH_HOME=$TORCH_HOME

So that if one would like to have a custom location

docker run -e TORCH_HOME=/models
